version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mtenk-pixelfed_web_1
      APP_PORT: 80
    ports:
      - "8088:80"

  web:
    image: pixelfed/pixelfed:v0.12.6
    restart: on-failure
    environment:
      - APP_NAME=Pixelfed
      - APP_ENV=production
      - APP_KEY=SLsIwivZxWcGTDZcLVUFuDDRI2Sw/lEAXlwPDaESwE0=
      - APP_DEBUG=false
      - APP_URL=http://192.168.1.45:8088
      - APP_DOMAIN=192.168.1.45
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pixelfed
      - DB_USERNAME=pixelfed
      - DB_PASSWORD=pixelfed
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    volumes:
      - ./data/storage:/var/www/storage
      - ./data/bootstrap:/var/www/bootstrap/cache
    depends_on:
      - db
      - redis

  worker:
    image: pixelfed/pixelfed:v0.12.6
    restart: on-failure
    command: php artisan horizon
    environment:
      - APP_NAME=Pixelfed
      - APP_ENV=production
      - APP_KEY=SLsIwivZxWcGTDZcLVUFuDDRI2Sw/lEAXlwPDaESwE0=
      - APP_DEBUG=false
      - APP_URL=http://192.168.1.45:8088
      - APP_DOMAIN=192.168.1.45
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pixelfed
      - DB_USERNAME=pixelfed
      - DB_PASSWORD=pixelfed
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    volumes:
      - ./data/storage:/var/www/storage
      - ./data/bootstrap:/var/www/bootstrap/cache
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=pixelfed
      - POSTGRES_USER=pixelfed
      - POSTGRES_PASSWORD=pixelfed
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: on-failure
    volumes:
      - ./data/redis:/data
