version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mtenk-peertube_peertube_1
      APP_PORT: 9000

  peertube:
    image: chocobozzz/peertube:production
    env_file:
      - .env
    volumes:
      - ./data/peertube/assets:/app/client/dist/static
      - ./data/peertube/data:/data
      - ./data/peertube/config:/config
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:6-alpine
    restart: on-failure
