version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mtenk-peertube_peertube_1
      APP_PORT: 9000

  peertube:
    image: chocobozzz/peertube:production
    environment:
      - POSTGRES_USER=peertube
      - POSTGRES_PASSWORD=peertube
      - POSTGRES_DB=peertube
      - PEERTUBE_DB_USERNAME=peertube
      - PEERTUBE_DB_PASSWORD=peertube
      - PEERTUBE_DB_NAME=peertube
      - PEERTUBE_DB_HOSTNAME=db
      - PEERTUBE_WEBSERVER_HOSTNAME=192.168.1.45
      - PEERTUBE_WEBSERVER_PORT=9999
      - PEERTUBE_WEBSERVER_HTTPS=false
      - PEERTUBE_ADMIN_EMAIL=admin@umbrel.local
      - PEERTUBE_SECRET=6e3b5e4c5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c
    volumes:
      - ./data/peertube/assets:/app/client/dist/static
      - ./data/peertube/data:/data
      - ./data/peertube/config:/config
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=peertube
      - POSTGRES_PASSWORD=peertube
      - POSTGRES_DB=peertube
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:6-alpine
    restart: on-failure